#!/bin/bash

shopt -s extglob
mv ./files/@(a*|A*) ./a
mv ./files/@(b*|B*) ./b
mv ./files/@(c*|C*) ./c
mv ./files/@(d*|D*) ./d
mv ./files/@(e*|E*) ./e
mv ./files/@(f*|F*) ./f
mv ./files/@(g*|G*) ./g
mv ./files/@(h*|H*) ./h
mv ./files/@(i*|I*) ./i
mv ./files/@(j*|J*) ./j
mv ./files/@(k*|K*) ./k
mv ./files/@(l*|L*) ./l
mv ./files/@(m*|M*) ./m
mv ./files/@(n*|N*) ./n
mv ./files/@(o*|O*) ./o
mv ./files/@(p*|P*) ./p
mv ./files/@(q*|Q*) ./q
mv ./files/@(r*|R*) ./r
mv ./files/@(s*|S*) ./s
mv ./files/@(t*|T*) ./t
mv ./files/@(u*|U*) ./u
mv ./files/@(v*|V*) ./v
mv ./files/@(w*|W*) ./w
mv ./files/@(x*|X*) ./x
mv ./files/@(y*|Y*) ./y
mv ./files/@(z*|Z*) ./z